name: custom_chatbot

services:
  custom-chatbot:
    build:
      context: ../
      dockerfile: ./docker/NonGPUDockerfile
    image: deepseek-chatbot
    container_name: custom-chatbot
    restart: unless-stopped
    env_file:
      - ./docker/.env
    ports:
      - "7860:7860"
    volumes:
      - ../:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    networks:
      - work_network

networks:
  work_network:
    driver: bridge